version: "3.7"

networks:
  petclinic:
    driver: bridge

services:
  app:
    image: sagordondevops/petclinic:v3
    build:
      context: .
      dockerfile: Dockerfile.multistage.v2
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
    networks:
      - petclinic
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    networks:
      - petclinic 